name: Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1  # Change to your preferred region
        run: |
          echo "Initializing Terraform"
          terraform init

      - name: Run Terraform Plan
        run: |
          echo "Running terraform plan"
          terraform plan -out=tfplan

      - name: Run Terraform Apply
        run: |
          echo "Applying terraform plan"
          terraform apply -auto-approve tfplan
