name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        run: |
          echo "terraform {
            required_providers {
              aws = {
                source  = \"hashicorp/aws\"
                version = \"~> 4.0\"
              }
            }
            required_version = \">= 1.0\"
          }" > terraform.tf

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
